### ISSUE TITLE
Add option to filter out fields when comparing JSON

### ISSUE THREAD

**Issue by selama1** [dreamproit/kosher-dill#8]
When comparing JSON to expected output, we would like to ignore some fields even when different.

For example, we have:
```
{
    "db_settings": {
        "last_db_update": "8/16/2022"
    },

...
}
```

The "last_db_update" field changes each time we update the database, and in tests where we recreate the db on each run, this number is going to change each time. We would like to ignore it an not report changes in such field. A possible syntax could be:

```
    expected_stdout:
      treat_as: json
      ignore_fields: [db_settings.last_db_update]
      file_path:  [*EXPECTED_STDOUT_DIR, 115hr1067ih.json]

```

Note: in this example, I specified the full path for `db_settings.last_db_update`. If this is hard to implement, we could alternatively just provide the field name (`last_db_update`) and ignore it whenever it appears.

Another possible feature (but lower priority) would be to add "compare_fields" as well, and in this case, only compare the fields in the list, and nothing else.
