### ISSUE TITLE
Calling "rm -f" doesn't work.

### ISSUE THREAD

**Issue by selama1** [dreamproit/kosher-dill#9]
When using the following test:
```
  - test: "Delete DB if exist"
    binary_path: rm
    arguments:
      [-f,/apps/US-House-Amendment-Parse-Tests/tests_data/LoadXML/xmldb/*]
    expected_return_code: 0
```

It looks like the `rm` command have no effect, and the files are not deleted. The test passes, so it does return code 0. It also doesn't matter if I use `rm` directly, or call `/bin/busybox`. Also, running the command manually from an interactive shell inside Docker does work.
